"""empty message

Revision ID: 08a52c410509
Revises: None
Create Date: 2016-05-22 21:34:56.629376

"""

# revision identifiers, used by Alembic.
revision = '08a52c410509'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ESP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=300), nullable=True),
    sa.Column('xpath', sa.String(length=500), nullable=True),
    sa.Column('is_qual', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ESP_xpath'), 'ESP', ['xpath'], unique=False)
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_name'), 'apps', ['name'], unique=True)
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('doctype', sa.String(length=55), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_name'), 'scenario', ['name'], unique=True)
    op.create_table('appinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('processtime', sa.Float(precision=15), nullable=False),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('misc', sa.String(length=200), nullable=True),
    sa.Column('fn_app', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fn_app'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contains',
    sa.Column('esp_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['esp_id'], ['ESP.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], )
    )
    op.create_table('esp_groups',
    sa.Column('esp_me_id', sa.Integer(), nullable=True),
    sa.Column('esp_equal_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['esp_equal_to_id'], ['ESP.id'], ),
    sa.ForeignKeyConstraint(['esp_me_id'], ['ESP.id'], )
    )
    op.create_table('qual_children',
    sa.Column('qual_esp_id', sa.Integer(), nullable=True),
    sa.Column('qual_child_esp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qual_child_esp_id'], ['ESP.id'], ),
    sa.ForeignKeyConstraint(['qual_esp_id'], ['ESP.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qual_children')
    op.drop_table('esp_groups')
    op.drop_table('contains')
    op.drop_table('appinfo')
    op.drop_index(op.f('ix_scenario_name'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_apps_name'), table_name='apps')
    op.drop_table('apps')
    op.drop_index(op.f('ix_ESP_xpath'), table_name='ESP')
    op.drop_table('ESP')
    ### end Alembic commands ###
