"""empty message

Revision ID: 20f25b9d3149
Revises: cd6ad7de756d
Create Date: 2016-06-09 15:29:58.488026

"""

# revision identifiers, used by Alembic.
revision = '20f25b9d3149'
down_revision = 'cd6ad7de756d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_name'), ['name'], unique=False)
        batch_op.drop_column('child_groups')


    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_groups', sa.VARCHAR(length=1000), nullable=True))
        batch_op.drop_index(batch_op.f('ix_group_name'))


    ### end Alembic commands ###
