"""empty message

Revision ID: 42497348e808
Revises: 08a52c410509
Create Date: 2016-05-22 21:42:07.982187

"""

# revision identifiers, used by Alembic.
revision = '42497348e808'
down_revision = '08a52c410509'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('fulfillmenttype', sa.String(length=100), nullable=True))
    op.add_column('scenario', sa.Column('schema', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'schema')
    op.drop_column('scenario', 'fulfillmenttype')
    ### end Alembic commands ###
