"""empty message

Revision ID: 77c6b91c6ddc
Revises: ed887f218146
Create Date: 2016-05-25 06:08:13.959540

"""

# revision identifiers, used by Alembic.
revision = '77c6b91c6ddc'
down_revision = 'ed887f218146'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qual_children')
    op.drop_table('esp_groups')
    with op.batch_alter_table('ESP', schema=None) as batch_op:
        batch_op.drop_column('not_equal')
        batch_op.drop_column('is_qual')
        batch_op.drop_column('requires_one')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ESP', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_one', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_qual', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('not_equal', sa.BOOLEAN(), nullable=True))

    op.create_table('esp_groups',
    sa.Column('esp_me_id', sa.INTEGER(), nullable=True),
    sa.Column('esp_equal_to_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['esp_equal_to_id'], ['ESP.id'], ),
    sa.ForeignKeyConstraint(['esp_me_id'], ['ESP.id'], )
    )
    op.create_table('qual_children',
    sa.Column('qual_esp_id', sa.INTEGER(), nullable=True),
    sa.Column('qual_child_esp_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['qual_child_esp_id'], ['ESP.id'], ),
    sa.ForeignKeyConstraint(['qual_esp_id'], ['ESP.id'], )
    )
    ### end Alembic commands ###
