"""empty message

Revision ID: cd6ad7de756d
Revises: 77c6b91c6ddc
Create Date: 2016-06-09 11:12:36.953582

"""

# revision identifiers, used by Alembic.
revision = 'cd6ad7de756d'
down_revision = '77c6b91c6ddc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(length=300), nullable=True),
    sa.Column('not_equal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_name'), ['name'], unique=False)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('qualifier_field', sa.String(length=100), nullable=True),
    sa.Column('child_groups', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_fields',
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['scenario.id'], )
    )
    op.create_table('scenario_groups',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], )
    )
    op.drop_table('contains')
    op.drop_table('ESP')
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_node', sa.String(length=200), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_column('root_node')

    op.create_table('ESP',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.VARCHAR(length=300), nullable=True),
    sa.Column('xpath', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contains',
    sa.Column('esp_id', sa.INTEGER(), nullable=True),
    sa.Column('scenario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['esp_id'], ['ESP.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], )
    )
    op.drop_table('scenario_groups')
    op.drop_table('group_fields')
    op.drop_table('group')
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_name'))

    op.drop_table('field')
    ### end Alembic commands ###
